import {
  Color,
  Padding,
  FontFamily,
  FontSize,
  Border,
} from "../../../GlobalStyles";

export const InfluencerManageAccountStyles = {
  scrollView: {
    flex: 1,
    backgroundColor: "#fff",
  },
  brandUpdateForm: {
    padding: 16,
  },
  userProfilePhoto: {
    flex: 1,
    backgroundColor: Color.colorWhite,
    padding: Padding.p_base,
    width: "100%",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: Padding.p_base,
  },
  profileImage: {
    width: 20,
    height: 20,
    borderRadius: 24,
    marginRight: Padding.p_base,
  },
  profilePhotoText: {
    fontSize: FontSize.size_lg,
    fontFamily: FontFamily.beVietnamProBold,
    width: "80%",
    textAlign: "center",
  },
  imageContainer: {
    alignItems: "center",
    marginBottom: 16,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  changePhotoText: {
    textAlign: "center",
    color: "#007BFF",
    marginBottom: 16,
  },
  formGroup: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: FontSize.size_3xl,
    fontFamily: FontFamily.beVietnamProBold,
    marginVertical: Padding.p_base,
    lineHeight: 28,
  },
  buttonContainer: {
    flexDirection: "column",
    justifyContent: "center",
    marginTop: Padding.p_base,
    gap: Padding.p_base,
    width: "100%",
    paddingHorizontal: Padding.p_base,
  },
  tipContainer: {
    flexDirection: "row",
    marginBottom: Padding.p_base,
    backgroundColor: Color.colorWhitesmoke,
    borderRadius: Border.br_xs,
    padding: Padding.p_base,
  },
  tipImage: {
    width: 48,
    height: 48,
    borderRadius: Border.br_xs,
  },
  tipTextContainer: {
    marginLeft: Padding.p_base,
    flex: 1,
  },
  tipTitle: {
    fontSize: FontSize.size_base,
    fontFamily: FontFamily.beVietnamProMedium,
    color: Color.colorSlategray_300,
    marginBottom: Padding.p_5xs,
    textAlign: "center",
    marginTop: 60,
  },
  tipDescription: {
    fontSize: FontSize.size_sm,
    fontFamily: FontFamily.beVietnamProRegular,
    color: "#637587",
    lineHeight: FontSize.size_base,
  },
  label: {
    marginBottom: 4,
    fontFamily: FontFamily.plusJakartaSansMedium,
    fontWeight: "500",
    fontSize: FontSize.size_base,
    color: Color.colorGray_100,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    borderRadius: Border.br_xs,
    backgroundColor: Color.colorAliceblue,
    marginTop: Padding.p_5xs,
    color: "#4F7A94",
    fontSize: FontSize.size_base,
    fontFamily: FontFamily.plusJakartaSansRegular,
  },
  textInput: {
    flex: 1,
    height: 40,
    borderRadius: Border.br_xs,
    backgroundColor: Color.colorAliceblue,
    paddingRight: Padding.p_base,
    color: "#4F7A94",
    fontSize: FontSize.size_base,
    fontFamily: FontFamily.plusJakartaSansRegular,
  },
  editIcon: {
    marginLeft: 8,
  },
  passwordIcon: {
    marginLeft: 8,
  },
  submitButton: {
    backgroundColor: "#007BFF",
    paddingVertical: 12,
    borderRadius: 4,
  },
  submitButtonText: {
    textAlign: "center",
    color: "#fff",
    fontSize: 16,
  },
  uploadButton: {
    backgroundColor: "#F0F2F5",
  },
  takePhotoButton: {
    backgroundColor: Color.colorRoyalblue,
    marginBottom: 20,
  },
  buttonText: {
    fontSize: FontSize.size_base,
    fontFamily: FontFamily.beVietnamProBold,
    color: Color.colorGray,
  },
  takePhotoButtonText: {
    color: Color.colorWhite,
  },
  previewContainer: {
    alignItems: "center",
    marginVertical: 20,
  },
  selectedImage: {
    width: 200,
    height: 200,
    borderRadius: 100,
  },
  confirmButtonContainer: {
    margin: "auto",
    width: "100%",
    marginTop: 100,
  },
  confirmButton: {
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Color.colorDodgerblue,
    borderRadius: Border.br_xs,
    paddingHorizontal: Padding.p_base,
  },
  confirmButtonText: {
    color: Color.colorWhitesmoke_100,
    fontFamily: FontFamily.interBold,
    fontSize: FontSize.size_sm,
    fontWeight: "700",
    letterSpacing: 0,
    lineHeight: 21,
    textAlign: "left",
  },
  avatarsContainer: {
    width: "100%",
    paddingVertical: 40,
    height: "auto",
    paddingHorizontal: Padding.p_base,
  },
  avatarContainer: {
    padding: 20,
    width: 190,
    borderRadius: Border.br_base,
    marginEnd: 16,
  },
  selectedAvatar: {
    borderWidth: 2,
    backgroundColor: Color.colorWhitesmoke_400,
    borderColor: Color.colorGainsboro_300,
  },
  avatarImage: {
    width: 150,
    height: 150,
  },
  divider: {
    width: "100%",
    height: 1,
    backgroundColor: Color.colorGainsboro_300,
    marginVertical: 12,
  },
  orText: {
    position: "absolute",
    left: "50%",
    top: -10,
    color: Color.colorDimgray,
    backgroundColor: "#fff",
    paddingHorizontal: 8,
  },
  helpcenter: {
    backgroundColor: "#fff",
    width: "100%",
    flex: 1,
  },
  headerContainer: {
    height: 72,
    marginTop: Padding.p_base,
    padding: Padding.p_base,
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerImage: {
    width: 24,
    height: 24,
  },
  headerText: {
    fontSize: 22,
    width: "90%",
    textAlign: "center",
    color: Color.colorGray_400,
    fontFamily: FontFamily.beVietnamProBold,
  },
  button: {
    height: 40,
    borderRadius: Border.br_xs,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: Padding.p_base,
    marginHorizontal: Padding.p_2xs,
    width: "100%",
  },
};
