/* InboxInterface.scss */
import { Color, Padding, FontFamily, FontSize, Border } from "../../GlobalStyles";

export const inboxStyles = {
  scrollViewContent: {
    flexGrow: 1,
    backgroundColor: Color.colorWhite,
  },
  inboxContainer: {
    width: "100%",
    backgroundColor: Color.colorWhite,
  },
  headerContainer: {
    paddingHorizontal: Padding.p_base,
    backgroundColor: Color.colorWhite,
    position:"relative",
    top:0,
    width:"100%",
    height:72
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    height: 72,
  },
  headerSide: {
    width: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: FontSize.size_lg,
    fontWeight: "700",
    fontFamily: FontFamily.beVietnamProBold,
    color: Color.colorGray_500,
  },
  newMessageButton: {
    width: 48,
    height: 48,
    justifyContent: "center",
    alignItems: "center",
  },
  newMessageIcon: {
    width: 24,
    height: 24,
  },
  searchContainer: {
    paddingHorizontal: Padding.p_base,
    backgroundColor: Color.colorWhite,
    height: 96,
  },
  searchContent: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Color.colorWhitesmoke_300,
    borderRadius: Border.br_xs,
    padding: Padding.p_xs,
  },
  searchIcon: {
    width: 24,
    height: 24,
  },
  searchInput: {
    flex: 1,
    fontFamily: FontFamily.beVietnamProRegular,
    fontSize: FontSize.size_base,
    color: Color.colorGray_500,
    marginLeft: 12,
  },
  conversationRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Padding.p_base,
    paddingVertical: 12,
    backgroundColor: Color.colorWhite,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  messageContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Padding.p_base,
    height: 72,
    backgroundColor: Color.colorWhite,
  },
  messageImage: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: Color.colorWhitesmoke_300,
    flexShrink: 0,
  },
  messageContent: {
    flex: 1,
    marginLeft: 14,
    overflow: "hidden",
  },
  messageTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 3,
  },
  messageTitle: {
    fontWeight: "700",
    fontFamily: FontFamily.beVietnamProBold,
    fontSize: FontSize.size_base,
    color: Color.colorGray_400,
    flex: 1,
    marginRight: 8,
  },
  messageTime: {
    fontSize: 12,
    color: Color.colorSlategray_200,
    fontFamily: FontFamily.beVietnamProRegular,
    flexShrink: 0,
  },
  messageStatus: {
    fontSize: FontSize.size_sm,
    color: Color.colorSlategray_200,
    fontFamily: FontFamily.beVietnamProRegular,
  },
  messagePreview: {
    fontFamily: FontFamily.beVietnamProRegular,
    fontSize: FontSize.size_sm,
    color: Color.colorSlategray_200,
  },
  spacer: {
    height: 20,
    width: "100%",
    backgroundColor: Color.colorWhite,
  },
  footer: {
    height: 76,
    paddingHorizontal: Padding.p_xl,
    justifyContent: "flex-end",
    flexDirection: "row",
    backgroundColor: "transparent",
    width:"auto",
    position:"absolute",
    bottom:30,
    right:30
  },
  newMessageFooterButton: {
    width: 56,
    height: 56,
    borderRadius: Border.br_xs,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Color.colorRoyalblue,
    elevation: 4,
  },
  addButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 56,
    height: 56,
    backgroundColor: Color.colorRoyalblue,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
  },
  addButtonText: {
    fontSize: 40,
    color: 'white',
  },
};
