import React from "react";
import { View, Text, StyleSheet } from "react-native";

// AI Content Insights card — influencer-only. Reads the cached aiInsights
// object produced by the backend (code stats + Gemini topics/summary, with a
// rule-based fallback). Shows: summary, what to post more/less, top formats,
// best hashtags. Renders nothing if there are no insights yet.
const Chip = ({ label, tone = "neutral" }) => (
  <View style={[styles.chip, tone === "good" && styles.chipGood, tone === "bad" && styles.chipBad]}>
    <Text style={[styles.chipText, tone === "good" && styles.chipTextGood, tone === "bad" && styles.chipTextBad]}>
      {label}
    </Text>
  </View>
);

const AiInsightsCard = ({ insights, platform }) => {
  if (!insights || !insights.ai) return null;
  const { ai, bestFormat, bestCaptionLength, topHashtags = [], postsAnalyzed, window, source } = insights;

  return (
    <View style={styles.card}>
      <View style={styles.headerRow}>
        <Text style={styles.title}>✨ AI Content Insights</Text>
        <Text style={styles.meta}>
          {postsAnalyzed ? `${postsAnalyzed} posts · ` : ""}{window || ""}
        </Text>
      </View>

      {ai.summary ? <Text style={styles.summary}>{ai.summary}</Text> : null}

      {/* What to post more / less */}
      {(ai.topTopics?.length || ai.weakTopics?.length) ? (
        <View style={styles.section}>
          {ai.topTopics?.length ? (
            <>
              <Text style={styles.sectionLabel}>Post more of</Text>
              <View style={styles.chipRow}>
                {ai.topTopics.map((t, i) => <Chip key={`t${i}`} label={t} tone="good" />)}
              </View>
            </>
          ) : null}
          {ai.weakTopics?.length ? (
            <>
              <Text style={[styles.sectionLabel, { marginTop: 10 }]}>Post less of</Text>
              <View style={styles.chipRow}>
                {ai.weakTopics.map((t, i) => <Chip key={`w${i}`} label={t} tone="bad" />)}
              </View>
            </>
          ) : null}
        </View>
      ) : null}

      {/* Recommendations */}
      {ai.recommendations?.length ? (
        <View style={styles.section}>
          <Text style={styles.sectionLabel}>Recommendations</Text>
          {ai.recommendations.map((r, i) => (
            <View key={`r${i}`} style={styles.recRow}>
              <Text style={styles.recBullet}>•</Text>
              <Text style={styles.recText}>{r}</Text>
            </View>
          ))}
        </View>
      ) : null}

      {/* Quick facts */}
      <View style={styles.factsRow}>
        {bestFormat ? (
          <View style={styles.fact}>
            <Text style={styles.factLabel}>Best format</Text>
            <Text style={styles.factValue}>{bestFormat}</Text>
          </View>
        ) : null}
        {bestCaptionLength ? (
          <View style={styles.fact}>
            <Text style={styles.factLabel}>Best caption</Text>
            <Text style={styles.factValue}>{bestCaptionLength}</Text>
          </View>
        ) : null}
      </View>

      {topHashtags?.length ? (
        <View style={styles.section}>
          <Text style={styles.sectionLabel}>Top hashtags</Text>
          <View style={styles.chipRow}>
            {topHashtags.map((h, i) => <Chip key={`h${i}`} label={`#${h.name}`} />)}
          </View>
        </View>
      ) : null}

      <Text style={styles.footer}>
        {source === "gemini" ? "Generated by AI from your recent posts" : "Based on your recent posts"}
      </Text>
    </View>
  );
};

const styles = StyleSheet.create({
  card: {
    marginHorizontal: 16,
    marginVertical: 12,
    padding: 18,
    borderRadius: 16,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ECECF2",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  headerRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  title: { fontSize: 16, fontWeight: "700", color: "#1c1c1e" },
  meta: { fontSize: 11, color: "#9aa3b2" },
  summary: { fontSize: 14, lineHeight: 20, color: "#3a3f47", marginBottom: 12 },
  section: { marginTop: 6, marginBottom: 6 },
  sectionLabel: { fontSize: 12, fontWeight: "700", color: "#637087", marginBottom: 6, textTransform: "uppercase", letterSpacing: 0.3 },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  chip: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 16, backgroundColor: "#f2f4f7" },
  chipText: { fontSize: 12, color: "#3a3f47", fontWeight: "500" },
  chipGood: { backgroundColor: "#E7F6EC" },
  chipTextGood: { color: "#1E8E4E" },
  chipBad: { backgroundColor: "#FDECEC" },
  chipTextBad: { color: "#C0392B" },
  recRow: { flexDirection: "row", marginBottom: 6 },
  recBullet: { fontSize: 14, color: "#1A80E5", marginRight: 8, lineHeight: 20 },
  recText: { flex: 1, fontSize: 14, lineHeight: 20, color: "#3a3f47" },
  factsRow: { flexDirection: "row", gap: 24, marginTop: 8, marginBottom: 4 },
  fact: {},
  factLabel: { fontSize: 11, color: "#9aa3b2", marginBottom: 2 },
  factValue: { fontSize: 15, fontWeight: "700", color: "#1c1c1e", textTransform: "capitalize" },
  footer: { fontSize: 10, color: "#b5bcc9", marginTop: 12, fontStyle: "italic" },
});

export default AiInsightsCard;
