import { Color, FontSize, Border, FontFamily, Padding } from "../../GlobalStyles";

export const chatStyles = {
  container: {
    flex: 1,
    width: "100%",
    backgroundColor: "#fff",
  },
  topbar: {
    width: "100%",
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  scrollContentContainer: {
    flexGrow: 1,
    paddingVertical: 8,
  },
  chatContent: {
    flex: 1,
    width: "100%",
  },
  messagesContainer: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    width: "100%",
  },
  bottomBar: {
    width: "100%",
    backgroundColor: "#F0F0F0",
    borderTopWidth: 1,
    borderTopColor: "#ddd",
  },

  // ── Deal bar ───────────────────────────────────────────────────────────────
  dealBar: {
    width: "100%",
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#fafafa",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  dealRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  dealActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  dealPrimaryBtn: {
    alignSelf: "flex-start",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#1A80E5",
    backgroundColor: "rgba(26,128,229,0.08)",
  },
  dealPrimaryText: {
    color: "#1A80E5",
    fontSize: 13,
    fontFamily: FontFamily.beVietnamProMedium,
    fontWeight: "600",
  },
  dealPendingText: {
    flex: 1,
    minWidth: 0,
    color: "#7a4d00",
    fontSize: 13,
    fontFamily: FontFamily.beVietnamProMedium,
  },
  dealSealedText: {
    flex: 1,
    minWidth: 0,
    color: "#1a8f5a",
    fontSize: 13,
    fontWeight: "700",
    fontFamily: FontFamily.beVietnamProBold,
  },
  dealClosedText: {
    flex: 1,
    minWidth: 0,
    color: "#666",
    fontSize: 13,
    fontWeight: "600",
    fontFamily: FontFamily.beVietnamProMedium,
  },
  chatActionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginTop: 8,
  },
  chatLinksRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginTop: 8,
  },
  linkBtn: {
    paddingVertical: 4,
  },
  linkText: {
    color: "#1A80E5",
    fontSize: 12,
    fontFamily: FontFamily.beVietnamProMedium,
    fontWeight: "600",
  },
  lockedBar: {
    width: "100%",
    paddingVertical: 20,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  lockedText: {
    color: "#888",
    fontSize: 13,
    textAlign: "center",
    fontFamily: FontFamily.beVietnamProRegular,
  },
  dealSealBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#1a8f5a",
  },
  dealSealText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "700",
    fontFamily: FontFamily.beVietnamProBold,
  },
  dealGhostBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#ccc",
  },
  dealGhostText: {
    color: "#666",
    fontSize: 13,
    fontFamily: FontFamily.beVietnamProMedium,
  },

  // ── Price modal ──────────────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalCard: {
    width: "100%",
    maxWidth: 360,
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111",
    fontFamily: FontFamily.beVietnamProBold,
    marginBottom: 8,
  },
  modalBody: {
    fontSize: 13,
    lineHeight: 19,
    color: "#666",
    fontFamily: FontFamily.beVietnamProRegular,
    marginBottom: 16,
  },
  priceInputRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 10,
    paddingHorizontal: 12,
    marginBottom: 18,
  },
  rupee: {
    fontSize: 20,
    color: "#111",
    fontWeight: "700",
    marginRight: 6,
  },
  priceInput: {
    flex: 1,
    fontSize: 20,
    paddingVertical: 12,
    color: "#111",
    fontFamily: FontFamily.beVietnamProBold,
    outlineStyle: "none",
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
  },
  modalCancel: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
  },
  modalCancelText: {
    color: "#666",
    fontSize: 14,
    fontFamily: FontFamily.beVietnamProMedium,
  },
  modalConfirm: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#1A80E5",
  },
  modalConfirmText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
    fontFamily: FontFamily.beVietnamProBold,
  },

  // ── Sent message (you) ────────────────────────────────────────────────────
  senderContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "flex-end",
    marginVertical: 2,
    paddingHorizontal: 8,
  },
  senderMessageContainer: {
    backgroundColor: Color.colorMediumslateblue,
    maxWidth: "75%",
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 2,
    paddingHorizontal: 10,
    paddingTop: 7,
    paddingBottom: 5,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  senderMessageRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    flexWrap: "wrap",
  },
  senderMessage: {
    fontSize: 15,
    fontFamily: FontFamily.beVietnamProRegular,
    color: "#fff",
    lineHeight: 22,
    flexShrink: 1,
  },
  senderTimeAgo: {
    fontSize: 11,
    color: "rgba(255,255,255,0.7)",
    textAlign: "right",
    marginTop: 2,
  },
  senderName: {
    display: "none",
  },

  // ── Received message ──────────────────────────────────────────────────────
  receiverContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "flex-end",
    marginVertical: 2,
    paddingHorizontal: 8,
    gap: 6,
  },
  receiverMessageContainer: {
    backgroundColor: Color.colorWhitesmoke_300,
    maxWidth: "75%",
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 2,
    borderBottomRightRadius: 10,
    paddingHorizontal: 10,
    paddingTop: 7,
    paddingBottom: 5,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 2,
    elevation: 1,
  },
  receiverName: {
    display: "none",
  },
  receiverMessageRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    flexWrap: "wrap",
  },
  receiverMessage: {
    fontSize: 15,
    fontFamily: FontFamily.beVietnamProRegular,
    color: "#111",
    lineHeight: 22,
    flexShrink: 1,
  },
  receiverTimeAgo: {
    fontSize: 11,
    color: "#999",
    textAlign: "right",
    marginTop: 2,
  },

  // ── Avatar ────────────────────────────────────────────────────────────────
  profileImage: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },

  // ── Unused legacy styles (kept to avoid import errors) ───────────────────
  lineHeight: { width: 2, backgroundColor: Color.colorGainsboro_400 },
  timeText: { textAlign: "left", lineHeight: 24, fontSize: FontSize.size_base },
  messageDot: { height: 16 },
  messageSmallDot: { borderRadius: Border.br_9xs, backgroundColor: Color.colorGray_200, width: 8, height: 8, marginTop: 4 },
  messageLine: { width: 40, alignItems: "center", justifyContent: "center", height: 72 },
  messageText: { fontWeight: "500", fontFamily: FontFamily.beVietnamProMedium, color: Color.colorBlack },
  messageTextWrapper: { alignSelf: "stretch" },
  messageTextContainer: { width: "auto", height: "auto" },
  messageTimeContainer: { width: "auto", height: 24 },
  messageContent: { flex: 1, paddingHorizontal: Padding.p_base, paddingVertical: Padding.p_base, marginLeft: 8, height: "auto", backgroundColor: Color.colorWhitesmoke_300, borderRadius: Border.br_base },
  messageRow: { flex: 1, flexDirection: "row", height: "auto", marginVertical: 6 },
  spacer: { height: 389, width: "100%" },
  footerSpacer: { height: 20, width: "100%", backgroundColor: Color.colorWhite },
};
